controller:
  motion_law_parameters:
    max_velocity: [15.0, 15.0, 15.0]
    max_acceleration: [14.00, 14.00, 14.00]

  cascade_controllers:
    - name: "joint1"
      inner:
# wc = 200
        Kp: 55.5604
        Ki: 877.8443
        Kd: 0.0
        filters_on_measure:
          - type: FirstOrderLowPassFilter
            time_constant: 0.006
        filters_on_derivative_error:
          - type: FirstOrderLowPassFilter
            time_constant: 0.004
          - type: NotchFilter
            natural_frequency: 620.0
            zeros_damping: 0.1
            poles_damping: 0.5
      outer:
        Kp: 5.5
        Ki: 0.0
        Kd: 0.0
        filters_on_measure:
          - type: FirstOrderLowPassFilter
            time_constant: 0.02

    - name: "joint2"
      inner:
# wc = 200
        Kp: 41.1135
        Ki: 740.2918
        Kd: 0.0
        filters_on_measure:
          - type: FirstOrderLowPassFilter
            time_constant: 0.007
        filters_on_derivative_error:
          - type: FirstOrderLowPassFilter
            time_constant: 0.004
          - type: NotchFilter
            natural_frequency: 750.0
            zeros_damping: 0.1
            poles_damping: 0.5
      outer:
        Kp: 4.0
        Ki: 0.0
        Kd: 0.0
        filters_on_measure:
          - type: FirstOrderLowPassFilter
            time_constant: 0.02

    - name: "joint3"
      inner:
# wc = 100
        Kp: 50.966
        Ki: 5.0967
        Kd: 0.0
        filters_on_measure:
          - type: FirstOrderLowPassFilter
            time_constant: 0.006
        filters_on_derivative_error:
          - type: FirstOrderLowPassFilter
            time_constant: 0.004
          - type: NotchFilter
            natural_frequency: 715.0
            zeros_damping: 0.1
            poles_damping: 0.4
      outer:
        Kp: 4.0
        Ki: 0.0
        Kd: 0.0
        filters_on_measure:
          - type: FirstOrderLowPassFilter
            time_constant: 0.02

model_parameters:
- 0.948908
- 0.000000
- -0.000000
- 0.000000
- -0.000000
- -0.000000
- -0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.711881
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.962037
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.000000
- 0.011849
- 0.117187
- 0.080816
- -0.015391
- -0.063763
- -0.052359